version: '1.0'
name: pipeline-20230930
displayName: pipeline-20230930
triggers:
  trigger: auto
  push:
    branches:
      prefix:
        - master
    paths:
      precise:
        - dist
  schedule:
    - cron: '* * * * * ? *'
stages:
  - name: stage-f7fcaa07
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 16.14.2
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run docs:build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
